# Copyright (c) 2024 Kk
#
# This software is released under the MIT License.
# https://opensource.org/licenses/MIT

require:
  - rubocop-rails

AllCops:
  TargetRubyVersion: 3.2

Rails:
  Enabled: true
